[package]
name = "now_rust_example"
version = "0.1.0"
edition = "2018"

[dependencies]
http = "0.1"
lambda_runtime = "*"

[dependencies.now_rust]
git = "https://github.com/anmonteiro/now-rust"
rev = "master"